---
apiVersion: v1
kind: Service
metadata:
  name: istio-egressgateway
spec:
  type: ClusterIP
  selector:
    istio: egressgateway
  ports:
  - name: http2
    port: 80
    targetPort: 8080
  - name: https
    port: 443
    targetPort: 8443
...