apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: productpage-gw-secret
  namespace: bookinfo
spec:
  commonName: secure-productpages
  dnsNames:
  - 'secure-productpage.apps.cluster-99549.dynamic.redhatworkshops.io'
  isCA: false
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: root-ca
  privateKey:
    algorithm: ECDSA
    size: 256
  secretName: productpage-gw-secret
status: {}
