apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: bookinfo

resources:
- ns.yaml
- servicemmeshmember.yaml
- ingressgw.yaml
- egressgw.yaml
- https://raw.githubusercontent.com/Maistra/istio/maistra-2.5/samples/bookinfo/platform/kube/bookinfo.yaml
